name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repo
    - name: Check out repository code
      uses: actions/checkout@v2

    # Step 2: Setup Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run pytest khusus test_train.py
    - name: Run tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest tests/test_train.py -v
